### ISSUE TITLE
Open directory as file exception when using zero global songs

### ISSUE THREAD

**Issue by KungFuFurby** [KungFuFurby/AddMusicKFF#264]
Split from #262, reported by nyanpasu64 through both #262 and #263.

This specific quote is noted from nyanpasu64, as reported through #263:
> Ideally I'd remove all global songs, but with 0 songs I get a C++ "open directory as file" exception

**Comment by nyanpasu64** [comment]
https://github.com/KungFuFurby/AddMusicKFF/blob/fabfabfc7fe271645932158317061cb99872b885/src/AddmusicK/AddmusicK.cpp#L231-L238

`openTextFile()` is completely unnecessary. I commented the line out and rebuilt the AMK binary, and was able to successfully generate one or multiple SPC files in `-norom` mode. The line was wrong to begin with; it overwrites the wrong song, replacing the last global song with the first command-line song, and so on.

Before the line was executed, `openTextFile` was *not* run for global songs. If I comment out the line, `openTextFile` is run for neither global nor local songs, until after `textFilesToCompile` is finished traversing.

AMK still works without this code, since the song data is correctly read later on by `compileMusic()` -> `Music::compile()` -> `Music::init()` -> `openTextFile()`. This properly writes into `musics[].text`, regardless if it was empty before (with the earlier `openTextFile()` commented out) or had the wrong contents (in master).
